learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learninglog.urls')),
]

learninglog/urls.py
"""" Defines urls for learning logs"""
from django.urls import path

#path fucntion maps urls to views
from . import views
app_name = 'learninglog'

urlpatterns = [
    #Home page
    path('',views.index,name='index'),
    #url for all topics
    path('topics/',views.topics,name='topics'),
    #url for individual topics
    path('topics/<int:topic_id>/', views.topic,name='topic')
]

learninglog/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """"A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string rep of the model"""
        return self.text
    
class Entry(models.Model):
    """something specific learnt about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """return a string rep of the model"""
        return f"{self.text[:50]}..."

learninglog/views.py
from django.shortcuts import render
from .models import Topic

# Create your views here.

def index(request):
    """homepage for the app"""
    return render(request, 'learninglog/index.html')


def topics(request):
    """"shows all the topics"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics' : topics}
    return render(request, 'learninglog/topics.html', context)

def topic(request,topic_id):
    """shows single topic"""
    topic= Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by("-date_added")
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learninglog/topic.html',context)

learninglog/templates/learninglog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=p, initial-scale=1.0">
    <title>Document</title>
</head>
<body>                                                                          
    <p>
        <a href="{% url 'learninglog:index'%}">Learning Log</a>
        <a href="{% url 'learninglog:topics'%}">Topics</a>
    </p>
    {% block content %}{% endblock content %}
    
</body>
</html>

learninglog/templates/learninglog/index.html
{% extends "learninglog/base.html"%}

{% block content %}

<p>Learning Log</p>
<p>Learning Log helps you keep track of your learning for any topic you're learning about</p>

{% endblock content %}

learninglog/templates/learninglog/topic.html
{%extends 'learninglog/base.html'%}

{%block content%}

<p>Topic</p>
<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added | date:'M d, Y H:i'}}</p>
        <p>{{ entry.text| linebreaks }}</p>
    </li>
    {% empty %}
    <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>


{% endblock content%}

learninglog/templates/learninglog/topics.html
{% extends "learninglog/base.html"%}

{% block content%}

<p>Topics</p>
<ul>
    {% for topic in topics%}
        <li>
            <a href="{% url 'learninglog:topic' topic.id %}">{{ topic }}</a>
        </li> 
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>


{% endblock content%}